# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "lightmix-0.16.1-SpCovNZSAgB6SIkcskMHbN58ISBkbV5x4-D6kVT2Fr9_";
    path = fetchzip {
      url = "https://github.com/haruki7049/lightmix/archive/refs/tags/0.16.1.tar.gz";
      hash = "sha256-6w13Os9jWdn2e1UpbRIlw27555NjBlvHVKa+BMTLEcs=";
    };
  }
  {
    name = "lightmix_filters-0.2.1-QAX9gW0PIgDNEA_-PewDIRhzE8rBNHml7MFLXKCtRDG3";
    path = fetchzip {
      url = "https://github.com/haruki7049/lightmix_filters/archive/refs/tags/0.2.1.tar.gz";
      hash = "sha256-w8eEj+N7MeQJ/xMvKH3VfI/TuXx5dKkcRAkCNjKJAQY=";
    };
  }
  {
    name = "lightmix_synths-0.2.1-6UeSjLneigCnYK-I-eiwtyA03mauljPMbDNVSYUfAlem";
    path = fetchzip {
      url = "https://github.com/haruki7049/lightmix_synths/archive/refs/tags/0.2.1.tar.gz";
      hash = "sha256-Mm6dcLI4XUiAE+G2QPGCUNeDuoOhz+zD9VODhQQCW/4=";
    };
  }
  {
    name = "riff_zig-0.2.1-J7H0A0x-AABK0wyA5y4uQxq5x95-RTPUGIwWd61cBTw7";
    path = fetchzip {
      url = "https://github.com/haruki7049/RIFF.zig/archive/refs/tags/0.2.1.tar.gz";
      hash = "sha256-qF3iKfj4RL8tLiy7K0MRdKBsuH1MosZu7DHTSmmzpN0=";
    };
  }
  {
    name = "zigggwavvv-0.3.0-iR5xWtfEAAAd1ca3u6kOrPIFzODMgHiUIZQWava6XIwD";
    path = fetchzip {
      url = "https://github.com/haruki7049/zigggwavvv/archive/refs/tags/0.3.0.tar.gz";
      hash = "sha256-NqcDSBngSK+7emPru4bTN/fqsoPA4zg90HkIMYJXygw=";
    };
  }
]
